language: node_js

sudo: required

node_js: '8'

cache:
  directories:
    - elm-stuff/build-artifacts
    - elm-stuff/packages
    - tests/elm-stuff/build-artifacts
    - tests/elm-stuff/packages
    - sysconfcpus
    - $HOME/.npm
    - node_modules

install:
  - npm install -g elm@0.19.0-bugfix2
  - npm install -g elm-test@0.19.0-beta8
  - npm install -g elm-format@0.8.0
  - npm install -g create-elm-app@2.0.7

script:
  - elm-format --validate src --elm-version=0.19
  - elm-test
  - npm install
  - elm-app build

deploy:
  provider: surge
  project: ./build/
  domain: luigi-app.surge.sh
  skip_cleanup: true
