language: node_js

sudo: required

node_js: '8'

cache:
  directories:
    - elm-stuff/build-artifacts
    - elm-stuff/packages
    - tests/elm-stuff/build-artifacts
    - tests/elm-stuff/packages
    - sysconfcpus
    - $HOME/.npm
    - node_modules

install:
  - npm install create-elm-app@1.10.4 -g

script:
  - elm-app test

deploy:
  provider: surge
  project: ./build/
  domain: luigi-app.surge.sh
  skip_cleanup: true
