language: node_js

sudo: required

node_js: "8"

cache:
  directories:
    - elm-stuff/build-artifacts
    - elm-stuff/packages
    - tests/elm-stuff/build-artifacts
    - tests/elm-stuff/packages
    - sysconfcpus
    - $HOME/.npm
    - node_modules

install:
  - npm install -g create-elm-app@5.22.0
  - npm install -g elm-format@0.8.2

script:
  - elm-format --validate src --elm-version=0.19
  - elm-app test
  - npm install
  - standard
  - elm-app build
  - mv ./build/index.html ./build/200.html

deploy:
  provider: surge
  project: ./build/
  domain: scalesmeister.surge.sh
  skip_cleanup: true
