language: node_js

sudo: required

node_js: '8'

cache:
  directories:
    - elm-stuff/build-artifacts
    - elm-stuff/packages
    - tests/elm-stuff/build-artifacts
    - tests/elm-stuff/packages
    - sysconfcpus
    - $HOME/.npm
    - node_modules

install:
  - npm install create-elm-app@2.0.3
  - npm install -g elm-format@0.8.0

script:
  - elm-format --validate src --elm-version=0.19
  - elm-app test
  - elm-app make src/Main.elm --output=/dev/null --yes --warn
  - npm install

deploy:
  provider: surge
  project: ./build/
  domain: luigi-app.surge.sh
  skip_cleanup: true
